:credentials:
  :login: username
  :password: mypassword
:owner: ownername
:repository: reponame
:labels_by_commit:
  api: Frontend
  webui: Frontend
  frontend: Frontend
  doc: Documentation
  backend: Backend
  ci: Test Suite
:labels_for_files:
  README.md: Documentation
  src/api/spec/README.md: Documentation
  src/api: Frontend
  src/backend: Backend
  dist/t:
    - Backend
    - Test Suite
  dist/obsworker:
    - Backend
    - Appliance
  dist/sysconfig.obs-server:
    - Backend
    - Appliance
  dist: Appliance
